### ISSUE TITLE
New maintainer needed ?

### ISSUE THREAD

**Issue by hubertlepicki** [jaswope/rack-reverse-proxy#43]
Guys,

this is small cool project yet current maintainer clearly has no time/will to maintain it. 

Is there someone better suited for the job who would like to take over?

If not, I'd be happy to help as it looks like I'll be using this library more and more in upcoming months.

**Comment by giedriusr** [comment]
What has been decided?

**Comment by kemper** [comment]
+1 on pushing a new release. I got everything working with the 0.4.4 gem and had confusion over the master docs and code being different. I eventually upgraded and pointed to the latest sha, but I'd prefer to rely on a published version and pushing a new one out will save others the trouble.

**Comment by waterlink** [comment]
Hello everyone,

Now I am a maintainer.

I have just released [0.8.1](https://rubygems.org/gems/rack-reverse-proxy/versions/0.8.1)

I will try to migrate relevant issues and PRs to the new repo: https://github.com/waterlink/rack-reverse-proxy

**Comment by bethesque** [comment]
:+1:

**Comment by giedriusr** [comment]
:+1:

**Comment by peppyheppy** [comment]
:+1:  Is this issue closed then?

**Comment by jaswope** [comment]
Yes, yes it is.

**Comment by waterlink** [comment]
Heads up. Merged bunch of latest PRs and released [0.9.0](https://github.com/waterlink/rack-reverse-proxy/releases/tag/v0.9.0)
